import HomePage from "@/components/Home/Index";
import { useProducts } from "@/hooks/use-product";
import { ListResponse, Product } from "@/interfaces/index";
import axiosInstanceServer from "@/utils/axiosInstanceServer";
import { GetStaticProps } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

interface HomeProps {
  initProducts: Product[] | null;
}
export default function Home({ initProducts }: HomeProps) {
  const [data, setData] = useState(initProducts);
  const { products, pagination } = useProducts();

  useEffect(() => {
    if (products) setData(products);
  }, [products]);

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage products={data} pagination={pagination} />
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const url = `/products`;
  const res: ListResponse<Product[] | null> = await axiosInstanceServer.get(
    url
  );

  return {
    props: {
      initProducts: res.data,
    },
    revalidate: 10,
  };
};
