import AccountPage from "@/components/Account/Index";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
const Account = () => {
  const router = useRouter();
  // Protected route
  useEffect(() => {
    if (!localStorage.getItem(process.env.TOKEN_NAME as string))
      router.push("/");
  }, []);
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AccountPage />
      </main>
    </>
  );
};

export default Account;
